### ISSUE TITLE
Network not working for packer

### ISSUE THREAD

**Issue by sean-abbott** [CpuID/packer-ubuntu-virtualbox#3]
Using this script, the created ovf file does not have a ssh connection available because it doesn't connect to nat.  I'm not sure if the best place to handle that is....

So I'm working around this by adding "modifyvm --connectcable1 on" to every downstream file, but I can't figure out how to set it in the output ovf file and have it actually cascade permanently.  The saved file doesn't maintain the connected cable for the nat.  

Which I realize is probably a virtualbox (5.1?) issue more than an issue with this, but if anyone else manages to figure out how to solve it...

**Comment by CpuID** [comment]
Interesting, I thought I had this issue but could SSH in still via the NAT'ed port forward outside of packer. In the end I just had a mismatched `ssh_username`, so unrelated.

Running Virtualbox 5.2.6 here, no issues now. @sean-abbott I'm going to close this, if you believe it's still an outstanding issue please feel free to reopen.
